server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: "exampleuser"
    password: "examplepass1234"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
logging:
  level:
    org.springframework.security: DEBUG
