spring:
  config:
    import: optional:file:../kodera-config/.env
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_User_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
logging:
  level:
    org.springframework.security: DEBUG
